# DeepIsaHOL Dockerfile
# Multi-stage build for containerizing Isabelle/HOL proof verification API

# =============================================================================
# Stage 1: Builder
# =============================================================================
# Force amd64 platform - Isabelle2025-2_linux.tar.gz contains x86_64 binaries
FROM --platform=linux/amd64 ubuntu:22.04 AS builder

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    openjdk-17-jdk \
    python3 \
    python3-pip \
    gnupg \
    apt-transport-https \
    && rm -rf /var/lib/apt/lists/*

# Install sbt
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add && \
    apt-get update && \
    apt-get install -y sbt && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Download and extract Isabelle
RUN echo "Downloading Isabelle 2025-2..." && \
    curl -sO https://isabelle.in.tum.de/dist/Isabelle2025-2_linux.tar.gz && \
    tar -xzf Isabelle2025-2_linux.tar.gz && \
    rm Isabelle2025-2_linux.tar.gz

# Download and extract AFP
RUN echo "Downloading AFP..." && \
    curl -sO https://www.isa-afp.org/release/afp-current.tar.gz && \
    tar -xzf afp-current.tar.gz && \
    rm afp-current.tar.gz && \
    mv afp-* afp

# Register AFP with Isabelle
RUN ./Isabelle2025-2/bin/isabelle components -u "./afp/thys/"

# Clone and build scala-isabelle dependency
RUN git clone https://github.com/dominique-unruh/scala-isabelle.git && \
    cd scala-isabelle && \
    sbt publishLocal

# Copy project files
COPY build.sbt /build/app/
COPY src /build/app/src/

WORKDIR /build/app

# Generate directories.scala with container paths
RUN cat > /build/app/src/main/scala/directories.scala << 'EOF'
/*
Mantainers:
Jonathan Julián Huerta y Munive huertjon[at]cvut[dot]cz

Isabelle/RL directories: Docker container configuration
NOTE: This file is auto-generated by the Dockerfile.
Do not edit manually - changes will be overwritten during Docker builds.
*/

package isabelle_rl

object Directories {
val isabelle_app = "/app/Isabelle2025-2/"
val isabelle_afp = "/app/afp/thys/"
val isabelle_rl = "/app/"
}
EOF

# Compile the project with sbt
RUN sbt compile

# =============================================================================
# Stage 2: Runtime
# =============================================================================
# Force amd64 platform to match builder stage
FROM --platform=linux/amd64 ubuntu:22.04 AS runtime

ENV DEBIAN_FRONTEND=noninteractive

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \
    python3 \
    python3-pip \
    polyml \
    libgomp1 \
    gnupg \
    apt-transport-https \
    curl \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# Install sbt (needed to run the gateway)
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add && \
    apt-get update && \
    apt-get install -y sbt && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy Isabelle from builder
COPY --from=builder /build/Isabelle2025-2 /app/Isabelle2025-2

# Copy AFP from builder
COPY --from=builder /build/afp /app/afp

# Copy compiled project from builder
COPY --from=builder /build/app /app

# Copy sbt cache for faster startup
COPY --from=builder /root/.sbt /root/.sbt
COPY --from=builder /root/.cache /root/.cache

# Copy scala-isabelle local publish
COPY --from=builder /root/.ivy2/local /root/.ivy2/local

# Copy docker-specific files
COPY docker/requirements.txt /app/docker/
COPY docker/api.py /app/docker/
COPY docker/entrypoint.sh /app/docker/

# Intento solución para jacobo (compatibilidad windows)
# Usamos dos2unix para limpiar el script y luego damos permisos
RUN dos2unix /app/docker/entrypoint.sh && chmod +x /app/docker/entrypoint.sh

# Install Python dependencies
RUN pip3 install --no-cache-dir -r /app/docker/requirements.txt

# Make entrypoint executable
RUN chmod +x /app/docker/entrypoint.sh

# Register AFP with Isabelle (ensure paths are correct in runtime)
RUN /app/Isabelle2025-2/bin/isabelle components -u "/app/afp/thys/"

# Expose the API port
EXPOSE 8000

# Set environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"
ENV PYTHONUNBUFFERED=1

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=120s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

# Run the entrypoint script
ENTRYPOINT ["/app/docker/entrypoint.sh"]
